services:
  scpsl:
    build: .
    container_name: scp-deadicated
    ports:
      - "7777:7777/udp"
    volumes:
      - ./config:/config:z
    environment:
      - PORT=7777
    userns_mode: keep-id
    restart: unless-stopped