version: "3.9"
services:
  scp-deadicated:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scp-deadicated
    ports:
      - "7777:7777/udp"
    restart: unless-stopped
    volumes:
      - ./config:/config:Z
    stdin_open: true
    tty: true
